env:
  global:
    - secure: "SffQztDMTYVOes3IpDPQY13aDw7ifzSxcpnyOr8vjwIqUH3Uohi0geu9+NmVrOj7m2YvSNyTdkLjwa6VIhSwqrOrb2n+CiKEsVgW5YnXtuKWv3twoT21ZQXPqTPz3gmIuNDbdemyU6Xb60Q7+KveFb0Ru8yJ6QHtmVSpUjfK5IDz81Nm96J1Zc+MsNdFNwfzp0e79oFHvBevK7wpIo0dF9ZgcStpibue5dqc2kHRobHGutNOGyB4RJHJ/+AS13Vqf9qEB95rKerYxeDx9h76Larzj9NNCD96gKMbFKNvM9596DnbY1dNN10OVzijB6BpSnm73GnXePQmjU2pWI14NKzHe49FACG7CvYC2f0IFK72uLwrqaxxATlv6peTp9zpfjSNnI2KK7T9jURTXMZY5M02tk5lgwTi5gy7EuMfWhZ0GJe4iR8dQru9Ci3MXsbjdRhg8ihsaOqaDV0rEs0z1XdKkQHgSQIjC6PewE/CtyegM4gxpwV5gl7YoSAWPkdG/00QO4jStEpN3r5eqs3D74qFF9+ihMYAB2BPOoU2IcNNoTubkfGV3xleUXdhHBlpEi5emfeI4MV2kkRLyUIiowDTpnnT0EI5tcO/Pzwluw7KZLfc1HxL4ahS/ZjMg8+pFVqoSmZIs3AlFYvjC1xDPQeogeDfV/oPd7GYMygE8P0="
    - GIT_COMMITTER_NAME=travis
    - GIT_COMMITTER_EMAIL=kuniko192002@gmail.com
    - GIT_AUTHOR_NAME=travis
    - GIT_AUTHOR_EMAIL=kuniko192002@gmail.com
language: java
jdk:
  - oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
  - git clone --quiet https://github.com/yosshio0426/mvn-repo.git repo
  - cd repo
  - git checkout gh-pages
  - cd ..
script:
  - ./gradlew check uploadArchives
after_script:
  - cd repo
  - git add .
  - git commit -m 'Update'
  - git push --quiet https://${GH_TOKEN}@github.com/yosshio0426/mvn-repo.git gh-pages 2> /dev/null
  - cd ..